CREATE TABLE IF NOT EXISTS users (
	`id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
    `userID` VARCHAR(36) UNIQUE NOT NULL,
    `username` VARCHAR(36) NOT NULL,
    `password` VARCHAR(36) NOT NULL,
    `created_at` DATETIME,
    PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;